# Generated by Django 5.2 on 2025-08-08 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='Id do Stripe'),
        ),
    ]
