# Generated by Django 5.2 on 2025-06-07 00:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Barbearia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('cor_primaria', models.CharField(blank=True, max_length=7, null=True)),
                ('cor_secundaria', models.CharField(blank=True, max_length=7, null=True)),
                ('telefone_whatsapp', models.CharField(blank=True, max_length=20, null=True)),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('proprietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barbearias', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BarbeariaRedeSocial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('url', models.TextField()),
                ('barbearia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redes_sociais', to='site_design.barbearia')),
            ],
        ),
        migrations.CreateModel(
            name='ConteudoSite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chave', models.CharField(max_length=50)),
                ('titulo', models.CharField(blank=True, max_length=100, null=True)),
                ('subtitulo', models.CharField(blank=True, max_length=150, null=True)),
                ('conteudo', models.TextField(blank=True, null=True)),
                ('cta_texto', models.CharField(blank=True, max_length=100, null=True)),
                ('cta_url', models.TextField(blank=True, null=True)),
                ('barbearia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conteudos_site', to='site_design.barbearia')),
            ],
        ),
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='profissionais/')),
                ('descricao', models.TextField(blank=True, null=True)),
                ('barbearia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profissionais', to='site_design.barbearia')),
            ],
        ),
        migrations.CreateModel(
            name='PromocaoEvento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='promocoes_eventos/')),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('barbearia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promocoes_eventos', to='site_design.barbearia')),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('preco', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='servicos/')),
                ('barbearia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicos', to='site_design.barbearia')),
            ],
        ),
    ]
