# Generated by Django 5.2 on 2025-06-10 20:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_design', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChaveConteudo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chave', models.CharField(max_length=50, unique=True)),
                ('descricao', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.RemoveField(
            model_name='conteudosite',
            name='barbearia',
        ),
        migrations.CreateModel(
            name='InformacaoSite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('categoria', models.CharField(choices=[('CONTEUDO_SITE', 'Conteúdo do site'), ('REDES_SOCIAIS', 'Redes sociais'), ('PROMOCOES', 'Promoções')], max_length=20)),
                ('titulo', models.CharField(blank=True, max_length=100, null=True)),
                ('subtitulo', models.CharField(blank=True, max_length=150, null=True)),
                ('conteudo', models.TextField(blank=True, null=True)),
                ('cta_texto', models.CharField(blank=True, max_length=100, null=True)),
                ('cta_url', models.URLField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='informacoes_site/')),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('barbearia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informacoes_site', to='site_design.barbearia')),
                ('chave', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='site_design.chaveconteudo')),
            ],
            options={
                'ordering': ['categoria', 'chave', 'titulo'],
                'unique_together': {('barbearia', 'categoria', 'chave')},
            },
        ),
        migrations.DeleteModel(
            name='BarbeariaRedeSocial',
        ),
        migrations.DeleteModel(
            name='ConteudoSite',
        ),
    ]
