# Generated by Django 5.2 on 2025-06-10 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_design', '0002_chaveconteudo_remove_conteudosite_barbearia_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='informacaosite',
            options={'ordering': ['categoria', 'chave', 'conteudo']},
        ),
        migrations.RemoveField(
            model_name='informacaosite',
            name='cta_texto',
        ),
        migrations.RemoveField(
            model_name='informacaosite',
            name='cta_url',
        ),
        migrations.RemoveField(
            model_name='informacaosite',
            name='subtitulo',
        ),
        migrations.RemoveField(
            model_name='informacaosite',
            name='titulo',
        ),
        migrations.AlterField(
            model_name='informacaosite',
            name='categoria',
            field=models.CharField(choices=[('CONTEUDO_SITE', 'Conteúdo do site'), ('REDES_SOCIAIS', 'Redes sociais'), ('PROMOCOES', 'Promoções')], max_length=50),
        ),
        migrations.AlterField(
            model_name='informacaosite',
            name='conteudo',
            field=models.TextField(null=True),
        ),
    ]
