# Generated by Django 5.2 on 2025-06-10 20:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_design', '0003_alter_informacaosite_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informacaosite',
            name='imagem',
        ),
        migrations.CreateModel(
            name='ImagensSite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('imagem', models.ImageField(upload_to='imagens_site/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('barbearia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens_site', to='site_design.barbearia')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
