# Generated by Django 5.2 on 2025-06-10 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_design', '0004_remove_informacaosite_imagem_imagenssite'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenssite',
            name='chave',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='site_design.chaveconteudo'),
        ),
    ]
