# Generated by Django 5.2 on 2025-06-10 22:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_design', '0005_imagenssite_chave'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfissionalServico',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('duracao_min', models.PositiveIntegerField(blank=True, null=True)),
                ('preco_especial', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_design.profissional')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_design.servico')),
            ],
            options={
                'ordering': ['profissional', 'servico'],
                'unique_together': {('profissional', 'servico')},
            },
        ),
        migrations.AddField(
            model_name='profissional',
            name='servicos',
            field=models.ManyToManyField(related_name='profissionais', through='site_design.ProfissionalServico', to='site_design.servico'),
        ),
    ]
