# Generated by Django 5.2 on 2025-08-10 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_design', '0006_profissionalservico_profissional_servicos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barbearia',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='barbearia',
            name='longitude',
        ),
        migrations.AddField(
            model_name='barbearia',
            name='google_maps_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL do Google Maps'),
        ),
    ]
