# Generated by Django 5.2 on 2025-08-10 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_design', '0007_remove_barbearia_latitude_remove_barbearia_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barbearia',
            name='google_maps_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
