# Generated by Django 5.2 on 2025-08-11 00:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_design', '0008_alter_barbearia_google_maps_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='barbearia',
            name='cor_destaque',
            field=models.CharField(blank=True, max_length=7, null=True, validators=[django.core.validators.RegexValidator('^#(?:[0-9a-fA-F]{3}){1,2}$', 'Informe a cor em HEX. Ex.: #A1B2C3')], verbose_name='Cor de destaque'),
        ),
        migrations.AlterField(
            model_name='barbearia',
            name='cor_primaria',
            field=models.CharField(blank=True, max_length=7, null=True, validators=[django.core.validators.RegexValidator('^#(?:[0-9a-fA-F]{3}){1,2}$', 'Informe a cor em HEX. Ex.: #A1B2C3')], verbose_name='Cor primária'),
        ),
        migrations.AlterField(
            model_name='barbearia',
            name='cor_secundaria',
            field=models.CharField(blank=True, max_length=7, null=True, validators=[django.core.validators.RegexValidator('^#(?:[0-9a-fA-F]{3}){1,2}$', 'Informe a cor em HEX. Ex.: #A1B2C3')], verbose_name='Cor secundária'),
        ),
    ]
